### ISSUE TITLE
Use of asterisk wildcard in some queries

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-sql-provider#1]
Some of the queries use the asterisk wildcard to get all the columns from a table, just to say a few:
- CountryCode.sql -> #getAll
- Domain.sql -> #getByLdhName, #searchByPartialNameWZone, #searchByNameWZone, ...
- Entity.sql -> #getByHandle, #getByDomain, #getAll, ...

This doesn't represent a problem (apparently), but it's a good practice and also a recommendation to improve performance, to list only the columns that are expected to be used. In this case, this columns are used by the classes `mx.nic.rdap.sql.objects.*DbObj`. So I recommend that instead of using the wildcard, the queries should return the columns expected by the java objects.

**Comment by pcarana** [comment]
Also, listing the column names in the queries could save some reading time to someone that wishes to modify the queries; yes: it's more text, but the query is more explicit.

**Comment by TheRedTrainer** [comment]
Verified. All the queries files (.sql) includes all the required columns listed, the asterisk wildcard were removed.
