### ISSUE TITLE
rdap_user.rus_name cannot contain an entity.ent_handle value

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-sql-provider#10]
If a rdap server needs to implement entities credentials (for registrant, administrative and/or technical users), the current rdap_user table structure doesn't allow it because the user name column (rus_name) can contains only 16 chars, instead of the 100 char length for entity name column ent_handle.

It is required to match the length for both columns in order to allow to any entity/contact being a rdap user too.

**Comment by pcarana** [comment]
The `rdap_user` table now allows a maximum of 100 chars to be consistent with the handles. This was fixed at commit 68b4cbc8b5ec721df94f95f6dbc94e64539955ff.

**Comment by TheRedTrainer** [comment]
Verified. The length for "rus_name" column was increased to 100 (in current testing db and db creation scripts)
![image](https://user-images.githubusercontent.com/22969079/31734099-3bbd7596-b403-11e7-87f4-e63d6b787c4b.png)

**Comment by pcarana** [comment]
Closing, fixed in Red Dog v1.2
