### ISSUE TITLE
Default values of config properties are loaded from code

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-sql-provider#11]
The default values of the properties:
- `zones`
- `is_reverse_ipv4_enabled`
- `is_reverse_ipv6_enabled`
- `nameserver_as_domain_attribute`

are loaded from code (see `mx.nic.rdap.sql.model.ZoneModel`) instead of being loaded from a configuration file. The values are expected to be at server file `WEB-INF/data-access.properties`, but they should be at `META-INF/sql_provider_configuration.properties`; if the implementer wishes to modify the values this could be done at the server file `WEB-INF/data-access.properties`.

**Comment by pcarana** [comment]
The default values are now loaded from `META-INF/sql_provider_configuration.properties`, if they wanted to be configured from the server, this could be done at server's file `WEB-INF/data-access.properties`.

**Comment by TheRedTrainer** [comment]
Verified. sql_provider_configuration.properties file includes the default configuration for properties like zones, is_reverse_ipv4_enabled, is_reverse_ipv6_enabled and nameserver_as_domain_attribute. If the user wants to modify the configuration for any of there properties, it could be modified in WEB-INF/data-access.properties file.
