### ISSUE TITLE
Ip_network columns that shouldn't be nullable are nullable

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-sql-provider#12]
ine_start_address_down and ine_end_address_down columns from ip_network are currently nullable values. However, these columns shouldn't allow null values because they contain critical data for ip network such as ip address (at least the last octets/segments).

**Comment by TheRedTrainer** [comment]
Verified. The columns were changed from "nullable" to "not nullable".

**Comment by pcarana** [comment]
Closing, fixed in Red Dog v1.2
