### ISSUE TITLE
Domain searches by name and nsLdhName ignore server configuration "allow_search_wildcards_anywhere"

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-sql-provider#2]
This happens in the object `mx.nic.rdap.sql.impl.DomainDAOImpl` at the functions _`searchByName()`_ and _`searchByNsLDHName()`_. Both of them have a similar code block:

```java
if (domainName.contains("*")) {
	List<String> labels = Arrays.asList(domainName.split("\\."));
	for (String label : labels) {
		if (label.contains("*") && !label.endsWith("*"))
			throw new BadRequestException("Patterns can only have an * at the end.");
	}
}
```

So, if the server is allowing the use of wildcards anywhere, this code is preventing to use the wildcard as expected. Technically this validation is done at **rdap-server** `mx.nic.rdap.server.RdapSearchRequest.validatePartialSearchValue(String valuePattern, boolean isEntity)`.

**Comment by TheRedTrainer** [comment]
Verified. If the user executes a domain search by name or nsLdhName using wildcards at the beginning and the server is configured to allow wildcards anywhere, the server executes the search correctly.
