### ISSUE TITLE
Typos in the use of word "Role"

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-sql-provider#3]
Some references to objects or to the word "role" are still used as "rol". Here's a list of them:

- **`mx.nic.rdap.sql.model.RoleModel`**
  - All the queries names, except "getMainEntityRole" (eg, getDomainRol, getEntityRol, ...)
  - All the search functions (eg. getDomainEntityRol, getNameserverEntityRol, ...)
- **Role.sql**
  - All the queries identifiers, except "getMainEntityRole".

**Comment by TheRedTrainer** [comment]
Verified. All the Role.sql and RoleModel references to the word "role" were fixed.
