### ISSUE TITLE
SQLSyntaxErrorException when the queries lines are trimmed

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-sql-provider#4]
Let's take this query at **CountryCode.sql** as an example:
```sql
SELECT * FROM {schema}.country_code;
```
So far there's no problem, but if I do this (there's no space after "*" nor before "FROM"):
```sql
SELECT *
FROM {schema}.country_code;
```
...bad things will happen when the query is executed. The issue is at `mx.nic.rdap.sql.QueryGroup` constructor, since every line of the query that is being read is concatenated to a `StringBuilder`; so for the example, the query that is being executed is **"SELECT \*FROM {schema}.country_code;"** which is invalid SQL.

**Comment by TheRedTrainer** [comment]
Verified. When the sql query includes a new line, this new line is treated as a space (" ") in order to avoid breaking the query.

Even if the queries in .sql files include a new line or spaces, they are executed correctly.
