### ISSUE TITLE
Test query for database is hardcoded

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-sql-provider#5]
Somehow this has been already discussed, since the comment at `mx.nic.rdap.sql.DatabaseSession.testDatabase()` line 34 proves that. Instead of hardcode the query, why not let it be configurable?

There's already a configuration file loaded at `loadDataSourceFromProperties`, my proposal is that this file could have the validation query and just in case that it isn't configured it could load the default query; something like:

**`mx.nic.rdap.sql.DatabaseSession`**
```java
/** The parameter "testQuery" is added to the function **/
private static void testDatabase(BasicDataSource ds, String testQuery) throws SQLException {
	try (Connection connection = ds.getConnection(); Statement statement = connection.createStatement();) {
		ResultSet resultSet = statement.executeQuery(testQuery);
		if (!resultSet.next()) {
			throw new SQLException("'" + testQuery+ "' returned no rows.");
		}
		int result = resultSet.getInt(1);
		if (result != 1) {
			throw new SQLException("'" + testQuery+ "' returned " + result);
		}
	}
}
...
private static DataSource loadDataSourceFromProperties(Properties config) throws InitializationException {
...
	/** And is loaded here **/
	// http://stackoverflow.com/questions/3668506
	String testQuery = config.getProperty("testQuery", "select 1");

	try {
		testDatabase(dataSource, testQuery);
	} catch (SQLException e) {
		throw new InitializationException("The database connection test yielded failure.", e);
	}
...
}
```

**Comment by TheRedTrainer** [comment]
Verified. If the database connection is initialized using the configuration parameters from configuration.properties , the test query is loaded from "testQuery" property. If the property doesn't appear in configuration.properties, the default value is "select 1".
