### ISSUE TITLE
Wildcards "%" and "_" can be used on partial searches

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-sql-provider#6]
The issue was originally reported at the server ([rdap-server issue 35](https://github.com/NICMx/rdap-server/issues/35)), but this issue is for the provider.

When a partial search is made using the only wildcard allowed "\*", I still can use other wildcards to get more information in the response. Here are some cases assuming that the minimum of characters allowed for the search is 5:
"_/domains?name=%%a%\*_" will search for all the domains that have the char 'a' in their names.
"_/domains?name=\_\_e\_\*_" will search for all the domains that the 3rd char of its name is the char 'e' followed by at least another char.

This wildcards can be used because the queries used for the searches use the sentence "LIKE", so they should be escaped if they are going to reach the query executed at DB. The escape could be made at the models (`mx.nic.rdap.sql.model`) just when the wildcard "*" is replaced by "%". The issue applies only for extended searches, so the models where the solution can be applied are:
- DomainModel
- EntityModel
- NameserverModel

**Comment by TheRedTrainer** [comment]
Verified. All the special chars used as a wildcard were escaped. The only wildcard allowed is * (asterisk). If an user executes the following searches, he receives the corresponding response:

http://localhost:8080/rdap-server/nameservers?name=_s*
{"rdapConformance":["rdap_level_0"],"errorCode":"404","title":"Object not found","description":""}

http://localhost:8080/rdap-server/nameservers?name=%s*
{"rdapConformance":["rdap_level_0"],"errorCode":"400","description":"The request must contain at least one of the following parameters: [ip, name]"}
