### ISSUE TITLE
Domain and nameserver searches aren't case insensitive

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-sql-provider#7]
This issue applies for the services:
- _/domain_
- _/domains?name_
- _/domains?nsLdhName_
- _/nameserver_
- _/nameservers?name_

In most of the services the label (domain name, nameserver and zone) is searched just as requested to the service, eg. "/domain/fOo.BaR" will search for the label "fOo" and zone "BaR". The issue is at 2 levels: **code** and **queries**.

At **code** because the values are never sanitized to use them as expected, something similar to the issue reported at the server ([rdap-server issue 42](https://github.com/NICMx/rdap-server/issues/42)) where the zone isn't case insensitive.

At **queries** because the implementation assumes that the parameters will be just as needed, so if my database stores the domains in uppercase I'm assuming that in `dom_ldh_name=?` the parameter will already be uppercase to find a match.

My suggestion is that at both levels (code and queries) the values will be used as lowercase, or if possible use operators that can ignore the case.

**Comment by pcarana** [comment]
Just to add more context to the issue: this happened using an Oracle DB. Apparently in MySQL this is not a problem when the default configuration is used.

**Comment by pcarana** [comment]
The use of lowercase will apply only to A-Label/LDH Name, the searches using U-Labels will be just as they where received by the server.

**Comment by TheRedTrainer** [comment]
Reopened. Almost all the validations use lowercase for ldh name and keep the original case for unicode name. However, the domain search uses lowercase for both ldh and unicode name. 


-- domain

> SELECT dom_id, dom_handle, dom_ldh_name, dom_unicode_name, dom_port43, zone_id FROM rdap.domain WHERE (dom_ldh_name='domain811' OR dom_unicode_name='domain811') AND zone_id = 3;

-- domains by name

> SELECT domain.dom_id, domain.dom_handle, domain.dom_ldh_name, domain.dom_unicode_name, domain.dom_port43, domain.zone_id FROM rdap.domain WHERE (dom_ldh_name='domain811' OR dom_unicode_name='DoMaIn811') AND domain.zone_id = 3 ORDER BY 1 LIMIT 11;

-- domains by nsLdhName

> SELECT DISTINCT (dom.dom_id), dom.dom_ldh_name, dom.dom_handle, dom.dom_port43, dom.zone_id, dom.dom_unicode_name FROM rdap.domain dom JOIN rdap.domain_nameservers dom_ns ON dom_ns.dom_id = dom.dom_id JOIN rdap.nameserver ns ON ns.nse_id = dom_ns.nse_id WHERE  (ns.nse_ldh_name LIKE 'ns0.domain811.com' OR ns.nse_unicode_name LIKE 'ns0.DoMaIn811.com') ORDER BY 1 LIMIT 11;

-- nameserver

> SELECT nse_id, nse_handle, nse_ldh_name, nse_port43, nse_unicode_name FROM rdap.nameserver nse WHERE nse.nse_ldh_name='ns0.domain811.com' OR nse.nse_unicode_name = 'ns0.DoMAiN811.com';

-- nameservers by name 

> SELECT DISTINCT(nse.nse_id), nse.nse_handle,nse.nse_ldh_name, nse.nse_port43, nse.nse_unicode_name FROM rdap.nameserver nse WHERE nse.nse_ldh_name='ns0.domain811.com' OR nse.nse_unicode_name='ns0.DoMAiN811.com' ORDER BY 1 LIMIT 11;



It is necessary to fix the unicode name validation for domain search, and keep the current case.

**Comment by pcarana** [comment]
The fix was made to be strict when searching a domain by its U-label and convert to lowercase the A-label of the name in the same search.

**Comment by TheRedTrainer** [comment]
Verified. All the validations use lowercase for ldh name and keep the original case for unicode name.


-- domain

> SELECT dom_id, dom_handle, dom_ldh_name, dom_unicode_name, dom_port43, zone_id FROM rdap.domain WHERE (dom_ldh_name='domain811' OR dom_unicode_name='dOmAIN811') AND zone_id = 3;

-- domains by name

> SELECT domain.dom_id, domain.dom_handle, domain.dom_ldh_name, domain.dom_unicode_name, domain.dom_port43, domain.zone_id FROM rdap.domain WHERE (domain.dom_ldh_name LIKE 'domain811%' OR domain.dom_unicode_name LIKE 'dOmAIN811%' ) AND domain.zone_id = 3 ORDER BY 1 LIMIT 21;

-- domains by nsLdhName

> SELECT DISTINCT (dom.dom_id), dom.dom_ldh_name, dom.dom_handle, dom.dom_port43, dom.zone_id, dom.dom_unicode_name FROM rdap.domain dom JOIN rdap.domain_nameservers dom_ns ON dom_ns.dom_id = dom.dom_id JOIN rdap.nameserver ns ON ns.nse_id = dom_ns.nse_id WHERE  (ns.nse_ldh_name LIKE '%.domain811%.com' OR ns.nse_unicode_name LIKE '%.dOmAIN811%.com') ORDER BY 1 LIMIT 21;

-- nameserver

> SELECT nse_id, nse_handle, nse_ldh_name, nse_port43, nse_unicode_name FROM rdap.nameserver nse WHERE nse.nse_ldh_name='ns0.domain811.com' OR nse.nse_unicode_name = 'ns0.dOmAIN811.com';

-- nameservers by name

> SELECT DISTINCT(nse.nse_id), nse.nse_handle,nse.nse_ldh_name, nse.nse_port43, nse.nse_unicode_name FROM rdap.nameserver nse WHERE nse.nse_ldh_name LIKE 'ns0%.domain811%.com' OR nse.nse_unicode_name LIKE 'ns0%.dOmAIN811%.com' ORDER BY 1 LIMIT 21;
